server:
  port: 8187
  servlet:
    context-path: /quotes-service

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:authbase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  liquibase:
    change-log: db/changelog/db.changelog-master.sql
